version: '3'

services:

    zookeeper:
        image: zookeeper
        restart: always
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zookeeper:2888:3888
        networks:
            - kafka-net

    kafka:
        image: confluentinc/cp-kafka:3.2.1
        restart: always
        ports:
            - 9092:9092
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_JMX_PORT: 9999
        networks:
            - kafka-net
        depends_on:
            - zookeeper
    kafka-manager:
        image: sheepkiller/kafka-manager
        restart: always
        ports:
            - 9000:9000
        environment:
            ZK_HOSTS: zookeeper:2181
        networks:
            - kafka-net
        depends_on:
            - zookeeper
            - kafka

networks:
    kafka-net:
        driver: bridge

