version: '3'

services:

    zookeeper:
        image: zookeeper
        restart: always
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zookeeper:2888:3888
        networks:
            - custom

    chronos:
        image: mesosphere/chronos:v3.0.1
        restart: always
        ports: 
            - 9090:9090
            - 9091:9091
        environment:
            PORT0: 9090
            PORT1: 9091
        command: --zk_hosts=zookeeper:2181 --master=zk://zookeeper:2181/mesos
        networks:
            - custom
        depends_on:
            - zookeeper

    marathon:
        image: mesosphere/marathon:v1.1.7
        restart: always
        command: --master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon
        ports:
            - 5055:8080
        networks:
            - custom
        depends_on:
            - zookeeper


    mesos_master:
        image: mesosphere/mesos-master:1.1.01.1.0-2.0.107.ubuntu1404
        restart: always
        ports: 
            - 5050:5050
        environment:
            MESOS_PORT: 5050
            MESOS_ZK: zk://zookeeper:2181/mesos
            MESOS_QUORUM: 1
            MESOS_HOSTNAME: localhost
            MESOS_REGISTRY: in_memory
            MESOS_LOG_DIR: /var/log/mesos
            MESOS_WORK_DIR: /var/tmp/mesos
        volumes:
            - ./log/mesos:/var/log/mesos
            - ./tmp/mesos:/var/tmp/mesos
        networks: 
            - custom
        depends_on:
            - zookeeper

    mesos_slave:
        image: mesosphere/mesos-slave:1.1.01.1.0-2.0.107.ubuntu1404
        restart: always
#        ports:
#            - 5051:5151
        environment:
            MESOS_PORT: 5051
            MESOS_MASTER: zk://zookeeper:2181/mesos
            MESOS_HOSTNAME: localhost
            MESOS_SWITCH_USER: 0
            MESOS_CONTAINERIZERS: docker,mesos
            MESOS_LOG_DIR: /var/log/mesos
            MESOS_WORK_DIR: /var/tmp/mesos
        volumes:
            - ./log/mesos:/var/log/mesos
            - ./tmp/mesos:/var/tmp/mesos
            - /var/run/docker.sock:/var/run/docker.sock
            - /cgroup:/cgroup
            - /sys:/sys
            - /usr/local/bin/docker:/usr/local/bin/docker
        networks:
            - custom
        depends_on:
            - zookeeper


networks:
    custom:
        driver: bridge

