version: '3'

services:

    zookeeper:
        image: zookeeper
        restart: always
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=localhost:2888:3888
        network_mode: host

    chronos:
        image: mesosphere/chronos:v3.0.2
        restart: always
        environment:
            PORT0: 9090
            PORT1: 9091
        command: --zk_hosts=localhost:2181 --master=zk://localhost:2181/mesos
        network_mode: host

    marathon:
        image: mesosphere/marathon:v1.5.5
        restart: always
        command: --master zk://localhost:2181/mesos --zk zk://localhost:2181/marathon
        network_mode: host


    mesos_master:
        image: mesosphere/mesos-master:1.4.1
        restart: always
        environment:
            MESOS_PORT: 5050
            MESOS_ZK: zk://localhost:2181/mesos
            MESOS_QUORUM: 1
            MESOS_HOSTNAME: localhost
            MESOS_REGISTRY: in_memory
            MESOS_LOG_DIR: /var/log/mesos
            MESOS_WORK_DIR: /var/tmp/mesos
        volumes:
            - ./log/mesos:/var/log/mesos
            - ./tmp/mesos:/var/tmp/mesos
        network_mode: host

    mesos_agent:
        image: mesosphere/mesos-agent:1.4.1
        restart: always
        environment:
            MESOS_PORT: 5051
            MESOS_MASTER: zk://localhost:2181/mesos
            MESOS_HOSTNAME: localhost
            MESOS_SWITCH_USER: 0
            MESOS_CONTAINERIZERS: docker,mesos
            MESOS_LOG_DIR: /var/log/mesos
            MESOS_WORK_DIR: /var/tmp/mesos
#            MESOS_LAUNCHER: posix
            MESOS_SYSTEMD_ENABLE_SUPPORT: "false"
        volumes:
            - ./log/mesos:/var/log/mesos
            - ./tmp/mesos:/var/tmp/mesos
            - /var/run/docker.sock:/var/run/docker.sock
            - /cgroup:/cgroup
            - /sys:/sys
            - /usr/local/bin/docker:/usr/local/bin/docker
        network_mode: host

